### ISSUE TITLE
Laravel 7 - Target class [swift.transport] does not exist.

### ISSUE THREAD

**Issue by vuldov** [agence-webup/laravel-sendinblue#24]
Hello,

I just create a new Laravel 7 project and I wanted to use sendinblue for sending emails (forgot password, ...).
`composer require webup/laravel-sendinblue`
After installing the package, I've got this error in the terminal :
```
> @php artisan package:discover --ansi

   Illuminate\Contracts\Container\BindingResolutionException 

  Target class [swift.transport] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:805
    801| 
    802|         try {
    803|             $reflector = new ReflectionClass($concrete);
    804|         } catch (ReflectionException $e) {
  > 805|             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    806|         }
    807| 
    808|         // If the type is not instantiable, the developer is attempting to resolve
    809|         // an abstract type such as an Interface or Abstract Class and there is

  1   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Webup\LaravelSendinBlue\SendinBlueServiceProvider))

      +16 vendor frames 
  18  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Webup\LaravelSendinBlue\SendinBlueServiceProvider))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.
```
The installation failed but the package exist in my projet (PhpStorm detect all files and class)
So I add the provider declaration and the configuration.
Now, when I call my application (with postman or any browser), it just return this error :

```Illuminate\Contracts\Container\BindingResolutionException: Target class [swift.transport] does not exist. in file /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 805

#0 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build('swift.transport')
#1 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(787): Illuminate\Container\Container->resolve('swift.transport', Array, true)
#2 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Foundation\Application->resolve('swift.transport', Array)
#3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(772): Illuminate\Container\Container->make('swift.transport', Array)
#4 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(1245): Illuminate\Foundation\Application->make('swift.transport')
#5 /var/www/vendor/webup/laravel-sendinblue/src/SendinBlueServiceProvider.php(19): Illuminate\Container\Container->offsetGet('swift.transport')
#6 [internal function]: Webup\LaravelSendinBlue\SendinBlueServiceProvider->boot()
#7 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#8 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#10 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#11 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#12 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(858): Illuminate\Container\Container->call(Array)
#13 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Foundation\Application->bootProvider(Object(Webup\LaravelSendinBlue\SendinBlueServiceProvider))
#14 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Webup\LaravelSendinBlue\SendinBlueServiceProvider), 20)
#15 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(842): array_walk(Array, Object(Closure))
#16 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#17 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(221): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#18 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Foundation\Application->bootstrapWith(Array)
#19 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(135): Illuminate\Foundation\Http\Kernel->bootstrap()
#20 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#21 /var/www/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#22 {main}
```

Does is compatible with Laravel 7 or did I miss something ?

Regards.

**Comment by EtoileFilante** [comment]
Hey!

You're right there is a problem, swift.transport was removed from illuminate and replaced with something else. See my PR here : https://github.com/agence-webup/laravel-sendinblue/pull/23

Just waiting for the merge & tagging

**Comment by vuldov** [comment]
Thank you, for your answer.
I didn't see your post, sorry for the repost.

Also, I can confirm that your patch works fine with laravel 7.
